name: 'Debug via SSH'
description: 'SSH to a GitHub Actions runner using ngrok'
branding:
  icon: 'terminal'  
  color: 'green'
inputs:
  SSH_PASS:
    description: 'Password for SSH session. Either this or SSH_PUBLIC_KEY need to be specified.'
    required: false
  SSH_PUBLIC_KEY:
    description: 'Public key for SSH session. Either this or SSH_PASS need to be specified.'
    required: false
  NGROK_AUTH_TOKEN:
    description: 'Authentification token for ngrok'
    required: true
  NGROK_REGION:
    description: 'Region for ngrok session'
    required: false
    default: 'us'
  NGROK_TIMEOUT:
    description: 'Timeout in seconds for ngrok session'
    default: 21500
  SSH_COMMAND_EXTRA_ARGS:
    description: Extra arguments to append to the printed ssh command. This will be appended to the command exactly as is.
runs:
  using: "composite"
  steps:
    - name: Check inputs
      env:
        INPUTS_SSH_PASS: ${{ inputs.SSH_PASS }}
        INPUTS_SSH_PUBLIC_KEY: ${{ inputs.SSH_PUBLIC_KEY }}
        INPUTS_NGROK_AUTH_TOKEN: ${{ inputs.NGROK_AUTH_TOKEN }}
        INPUTS_NGROK_TIMEOUT: ${{ inputs.NGROK_TIMEOUT }}
      run: |
        if [ -z "$INPUTS_SSH_PASS" ] && [ -z "$INPUTS_SSH_PUBLIC_KEY" ]
        then
          echo "SSH_PASS or SSH_PUBLIC_KEY needs to be passed in the 'with' field."
          exit 1
        fi

        if [ -z "$INPUTS_NGROK_AUTH_TOKEN" ]
        then
          echo "NGROK_AUTH_TOKEN needs to be passed in the 'with' field."
          exit 1
        fi

        number_pattern='^[1-9][0-9]*$'
        if ! [[ "$INPUTS_NGROK_TIMEOUT" =~ $number_pattern ]]
        then
          echo "NGROK_TIMEOUT needs to be an integer."
          exit 1
        fi
      shell: bash
    - name: Meet OS specific prerequisites
      env:
        INPUTS_SSH_PASS: ${{ inputs.SSH_PASS }}
        INPUTS_SSH_PUBLIC_KEY: ${{ inputs.SSH_PUBLIC_KEY }}
      run: |
        if($env:RUNNER_ARCH -eq 'ARM64')
        {
          $arch = 'arm64'
        }
        else
        {
          $arch = 'amd64'
        }
        if($env:RUNNER_OS -eq 'Linux')
        {
          printf "# Preparing environment..."
            echo "ngrok-v3-stable-linux-$arch.zip" > ngrok_zip_name
            whoami > ssh_user
          printf " [DONE]\n\n"

          if ($env:INPUTS_SSH_PUBLIC_KEY)
          {
            echo "# Add the SSH public key"
              mkdir -p "/home/$(cat ssh_user)/.ssh"
              echo $env:INPUTS_SSH_PUBLIC_KEY >> "/home/$(cat ssh_user)/.ssh/authorized_keys"
          }
          if ($env:INPUTS_SSH_PASS)
          {
            echo "# Change the SSH user password"
              echo "$($env:INPUTS_SSH_PASS)`n$($env:INPUTS_SSH_PASS)" | sudo passwd "$(cat ssh_user)"
          }
        }
        elseif($env:RUNNER_OS -eq 'macOS')
        {
          printf "# Preparing environment..."
            echo "ngrok-v3-stable-darwin-$arch.zip" > ngrok_zip_name
            echo "root" > ssh_user
          printf " [DONE]\n\n"
  
          echo "# Permit login as root user"
            echo 'PermitRootLogin yes' | sudo tee -a /etc/ssh/sshd_config >/dev/null
            sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
            sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

          if ($env:INPUTS_SSH_PUBLIC_KEY)
          {
            echo "# Add the SSH public key"
              sudo mkdir -p "/var/root/.ssh"
              echo $env:INPUTS_SSH_PUBLIC_KEY | sudo tee -a "/var/root/.ssh/authorized_keys"
          }
          if ($env:INPUTS_SSH_PASS)
          {
            echo "# Change the SSH user password"
              echo "$($env:INPUTS_SSH_PASS)`n$($env:INPUTS_SSH_PASS)" | sudo passwd "root"
          }
        }
        elseif($env:RUNNER_OS -eq 'Windows')
        {
          printf "# Preparing environment..."
            echo "ngrok-v3-stable-windows-$arch.zip" > ngrok_zip_name
            echo $env:UserName > ssh_user
          printf " [DONE]\n\n"
          
          # OpenSSH Server is only already installed on windows-2025.
          if ((Get-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0).State -ne 'Installed') {
            echo "# Install SSH server"
              # winget is only already installed on windows-2025
              # issue for windows-11-arm: https://github.com/actions/runner-images/issues/14083
              if (-not (Get-Command winget -CommandType Application -ErrorAction SilentlyContinue)) {
                Install-Module -Name Microsoft.WinGet.Client -Repository PSGallery -Force
                # windows-11-arm needs winget's repair command to be ran before it's available
                # https://github.com/actions/runner-images/issues/14083
                Repair-WinGetPackageManager -AllUsers -Latest -Force
              }

              # Typically you'd use `Add-WindowsCapability` but it takes an incredibly long time
              # on GH Actions due to having to re-apply Windows updates (measured time ~20 minutes):
              # https://www.elevenforum.com/t/why-is-openssh-an-optional-feature-and-takes-ages-to-install-add-optional-feature.37224/
              winget install -e --silent --accept-package-agreements --accept-source-agreements --id Microsoft.OpenSSH.Preview
          }

          echo "# Add Firewall rule to allow inbound TCP connection on local port 22"
            New-NetFirewallRule -Name ngrok -DisplayName 'ngrok' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

          echo "# Start the SSH server"
            net start sshd

          if ($env:INPUTS_SSH_PUBLIC_KEY)
          {
            echo "# Add the SSH public key"
              # Authorized SSH keys for administrative users need to be added to C:\ProgramData\ssh\administrators_authorized_keys
              # See: https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#administrative-user
              echo $env:INPUTS_SSH_PUBLIC_KEY >> "$env:ProgramData\ssh\administrators_authorized_keys"
              icacls.exe "$env:ProgramData\ssh\administrators_authorized_keys" /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"
              if ($LASTEXITCODE -ne 0) {
                Exit $LASTEXITCODE
              }
          }
          if ($env:INPUTS_SSH_PASS)
          {
            echo "# Change the SSH user password"
              net user $env:UserName $env:INPUTS_SSH_PASS
          }
        }
      shell: pwsh

    - name: Install and setup ngrok
      env:
        INPUTS_NGROK_AUTH_TOKEN: ${{ inputs.NGROK_AUTH_TOKEN }}
      run: |
        echo "# Install ngrok"
          curl https://bin.equinox.io/c/bNyj1mQVY4c/$(cat ngrok_zip_name) --output ngrok.zip
          unzip ngrok.zip
          chmod +x ./ngrok

        echo "# Set ngrok with the given authentification token"
          ./ngrok authtoken "$INPUTS_NGROK_AUTH_TOKEN"
      shell: bash

    - name: Start ngrok
      env:
        INPUTS_SSH_COMMAND_EXTRA_ARGS: ${{ inputs.SSH_COMMAND_EXTRA_ARGS }}
        INPUTS_NGROK_REGION: ${{ inputs.NGROK_REGION }}
        INPUTS_NGROK_TIMEOUT: ${{ inputs.NGROK_TIMEOUT }}
      run: |
        printf "# Starting ngrok..."
          ./ngrok tcp 22 --log ".ngrok.log" --region "$INPUTS_NGROK_REGION" &
        printf " [DONE]\n\n"

        printf "# Waiting for '.ngrok.log' file to be properly generated..."
          while ! grep -osqE "tcp://(.+)" .ngrok.log;do
            sleep 1
            if grep -sq "command failed" .ngrok.log
            then
              exit 1
            fi
          done
        printf " [DONE]\n\n"

        ssh_string=$(grep -oE "tcp://(.+)" .ngrok.log | sed "s/tcp:\/\//ssh $(cat ssh_user)@/" | sed "s/:/ -p /")
        continue_path=$(eval echo ~$(cat ssh_user)/continue)
        time="$INPUTS_NGROK_TIMEOUT"

        continue_test_cmd=(test ! -e "$continue_path")
        if [ "$RUNNER_OS" = 'macOS' ]
        then
          continue_test_cmd=(sudo "${continue_test_cmd[@]}")
        fi

        while "${continue_test_cmd[@]}" && [ $time -gt 1 ]
        do
          echo ""
          echo "#################"
          echo "# Connect to this runner using:"
          echo "#########################################"
          echo "$ssh_string" "$INPUTS_SSH_COMMAND_EXTRA_ARGS"
          echo "#########################################"
          echo "#"
          echo "# Allow workflow to continue using:"
          echo "#########################################"
          echo "bash -c \"touch $continue_path\""
          echo "#########################################"
          echo "#"
          echo "# SSH session time left:"
          echo "########################################"
          printf '#%-14s%dh:%02dm:%02ds%-14s#\n' '' $(($time/3600)) $(($time%3600/60)) $(($time%60)) ''
          echo "########################################"
          echo ""
          
          sleep 10
          time=$((time-10))
        done

        echo "# SSH session terminated. Allowing workflow to continue..."
      shell: bash
